CXX = g++

ifeq ($(OS),Windows_NT)
  RM=del
  EXT=.exe
else
  RM=rm
  EXT=
endif


L714_258.o: L714_258.cpp L714_258.hpp
        $(CXX) -c L714_258.cpp -o L714_258.o


.PHONY: clean
clean :
        $(RM) *.o *.exe